spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: otus-spring
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongo.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  level:
    root: info
  file:
    name: logfile.log
