spring:
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false
test:
  rightAnswersCountToPass: 3
  questionCount: 5
  locale: ru-RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv
logging:
  level:
    root: error
---
spring:
  config:
    activate:
      on-profile: test
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false
test:
  rightAnswersCountToPass: 3
  questionCount: 5
  locale: en-US
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv